### ISSUE TITLE
Pomegranate Package dependency

### ISSUE THREAD

**Issue by Rachel-Gray** [nkschaefer/ad-libs#4]
Hi,
Looking forward to using ad-libs for my dataset. I am having trouble with the pomegranate package. Installing pomegranate through either of the three methods (pip, conda, github download) described here (https://pomegranate.readthedocs.io/en/latest/install.html) works fine and I have no apparent issues appear on downloading:
`pip install pomegranate`

`Successfully built pomegranate
Installing collected packages: pomegranate
Successfully installed pomegranate-0.14.8`

 When I open python on my server and import pomegranate there are no complaints. 

However, when I then go to run the example given for adlibs I get the error: 

` File "bin/adlibs.py", line 5, in <module>
    import pomegranate
ImportError: No module named pomegranate
`
I was wondering if there is a specific version of pomegranate that I should be using? I am calling version 2.7 of python when I run ad-libs as well. Any advice on running this would be greatly appreciated. 

Thanks.

**Comment by nkschaefer** [comment]
Hey - thanks for your interest in the program and sorry for the delay. It looks like the way to install certain things has changed and this was all written in python2.7. I've updated everything to python3 and added an environment.yml file to help install dependencies through anaconda (see README). I just tested this, and importing pomegranate seems to work fine now on my end. Please let me know if this solves the problem. Thanks!
